print("__   _______")
print("\ \ / /  _  |")
print(" \ V /| | | |")
print("  \ / | | | |")
print("  | | | |_| |")
print("  \_/  \___/ ")
print("hi, whats your name?")
name = input("whats ur name?")
print(f"hi {name} how is life?")
life = input("how is life?")
print(f"i am glad your life is {life}")
food = input(f"whats your favorite food?")
print("oh...")
print(f"its {food}?")
print("well...")
print("I dont judge.")
dogs = input("whats your dogs breed?")
print(f"i love all dogs including {dogs}'s")
rateing = input("rate me on a scale from 1-10")
print(f"thank you for rating the project an {rateing}!")
print("BYEE")